writing:
    path:     /
    defaults: { _controller: "PromptBundle:Writing:index" }

writing_show:
    path:     /{id}/show
    defaults: { _controller: "PromptBundle:Writing:show" }

writing_new:
    path:     /new
    defaults: { _controller: "PromptBundle:Writing:new" }

writing_create:
    path:     /create
    defaults: { _controller: "PromptBundle:Writing:create" }
    methods:  POST

writing_edit:
    path:     /{id}/edit
    defaults: { _controller: "PromptBundle:Writing:edit" }

writing_update:
    path:     /{id}/update
    defaults: { _controller: "PromptBundle:Writing:update" }
    methods:  [POST, PUT]

writing_delete:
    path:     /{id}/delete
    defaults: { _controller: "PromptBundle:Writing:delete" }
    methods:  [POST, DELETE]
