<?php

namespace PromptBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromptPollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromptPollRepository extends EntityRepository
{
}
